[project]
name = "control-gastos"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "python-dotenv>=1.2.3",
]

[dependency-groups]
cron = [
    "apscheduler>=3.11.3",
]
frontend = [
    "streamlit>=1.63.0",
]
sheets = [
    "gspread>=6.2.1",
]
